[project]
name = "votekit-durham"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.1.0",
    "votekit>=3.2.1",
]
